version: '3.9'

services:
  db:
    container_name: igslog-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/igslog-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

