version: '3.8'
services:
  next:
    build: .
    ports:
      - '9001:3000'
    #volumes:
    #  - .:/usr/app
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.db
    ports:
      - '5432:5432'
