version: '3.8'
services:
  next:
    build: .
    ports:
      - '9002:3000'
    volumes:
      - /home/wicherixen/Dev/upload:/usr/app/public/upload:rw
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ../db/:/var/lib/postgresql/data/:rw
    env_file:
      - .env.db
    environment:
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5433:5432'
